# Generated by Django 2.2.5 on 2022-04-14 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='文件名')),
                ('parent', models.IntegerField(verbose_name='所属文件夹')),
                ('file', models.FileField(upload_to='', verbose_name='服务器路径')),
                ('groupID', models.IntegerField(verbose_name='所属组')),
                ('owner', models.EmailField(max_length=254, verbose_name='创建人')),
                ('download', models.PositiveIntegerField(default=0, verbose_name='下载量')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 1, 4, 275322), verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='路径名')),
                ('groupID', models.IntegerField(verbose_name='所属组')),
                ('is_root', models.BooleanField(default=False, verbose_name='是否为根')),
                ('parent', models.IntegerField(default=-1, verbose_name='上级目录')),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path_id', models.IntegerField(verbose_name='根节点ID')),
                ('file_count', models.PositiveIntegerField(verbose_name='文件数量')),
                ('file_size_count', models.PositiveIntegerField(verbose_name='文件总大小')),
                ('file_limit', models.PositiveIntegerField(default=104857600, verbose_name='组文件大小限制')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='account.WorkGroup', verbose_name='组文件')),
            ],
        ),
    ]
