# Generated by Django 3.1.4 on 2021-05-10 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20210508_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 12, 36, 57, 995362), verbose_name='创建日期'),
        ),
    ]
