# Generated by Django 3.1.4 on 2021-05-15 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20210515_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 12, 32, 55, 308910), verbose_name='创建日期'),
        ),
    ]
