# Generated by Django 3.1.4 on 2021-05-17 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_auto_20210517_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 21, 49, 137189), verbose_name='创建日期'),
        ),
    ]
