# Generated by Django 3.1.4 on 2021-05-17 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0015_auto_20210517_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 24, 3, 372206), verbose_name='创建日期'),
        ),
    ]
