# Generated by Django 3.1.4 on 2021-05-17 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0017_auto_20210517_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 27, 21, 643192), verbose_name='创建日期'),
        ),
    ]
