# Generated by Django 3.1.4 on 2021-01-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210110_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='leader',
            field=models.EmailField(default='admin@admin.com', max_length=50, verbose_name='组长'),
            preserve_default=False,
        ),
    ]
