# Generated by Django 3.1.4 on 2021-03-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210301_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workgroups',
        ),
        migrations.AddField(
            model_name='user',
            name='groupID',
            field=models.IntegerField(default=-1, verbose_name='组序号'),
        ),
    ]
