# Generated by Django 3.1.4 on 2021-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210312_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='unread_mail_num',
            field=models.IntegerField(default=0, verbose_name='未读信息数量'),
        ),
    ]
