# Generated by Django 3.1.4 on 2021-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_workgroup_unread_mail_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='unread_mail_num',
        ),
        migrations.AddField(
            model_name='user',
            name='unread_mail_num',
            field=models.IntegerField(default=0, verbose_name='未读信息数量'),
        ),
    ]
