# Generated by Django 3.1.4 on 2021-04-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='日程标题')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='简介')),
                ('userID', models.IntegerField(default=-1, verbose_name='创建人ID')),
                ('groupID', models.IntegerField(default=-1, verbose_name='组ID')),
                ('priority_level', models.PositiveSmallIntegerField(default=1, verbose_name='优先级')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '日程',
                'verbose_name_plural': '日程',
            },
        ),
    ]
