# Generated by Django 2.2.5 on 2022-04-14 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='日程标题')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='简介')),
                ('userID', models.IntegerField(default=-1, verbose_name='创建人ID')),
                ('groupID', models.IntegerField(default=-1, verbose_name='组ID')),
                ('priority_level', models.PositiveSmallIntegerField(default=1, verbose_name='优先级')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '日程',
                'verbose_name_plural': '日程',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='agenda.Agenda', verbose_name='日程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_agenda', to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
        ),
    ]
