# Generated by Django 3.1.4 on 2021-05-08 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='agenda.agenda', verbose_name='日程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_agenda', to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
        ),
    ]
