# Generated by Django 3.1.4 on 2021-03-05 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='last_time',
        ),
        migrations.AddField(
            model_name='agenda',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
            preserve_default=False,
        ),
    ]
