# Generated by Django 3.1.4 on 2021-03-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210305_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='groupID',
            field=models.IntegerField(default=-1, verbose_name='组ID'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='userID',
            field=models.IntegerField(default=-1, verbose_name='创建人ID'),
        ),
    ]
