# Generated by Django 3.1.4 on 2021-05-08 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0002_auto_20210508_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 12, 52, 0, 593783), verbose_name='创建时间'),
        ),
    ]
