# Generated by Django 3.1.4 on 2021-03-13 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0003_auto_20210313_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 14, 11, 14, 970877), verbose_name='创建时间'),
        ),
    ]
