# Generated by Django 3.1.4 on 2021-04-08 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0004_auto_20210313_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 14, 42, 739213), verbose_name='创建时间'),
        ),
    ]
