# Generated by Django 3.1.4 on 2021-05-13 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0004_auto_20210510_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 11, 28, 7, 206344), verbose_name='创建时间'),
        ),
    ]
