# Generated by Django 3.1.4 on 2021-04-16 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0005_auto_20210408_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 10, 43, 41, 733028), verbose_name='创建时间'),
        ),
    ]
