# Generated by Django 3.1.4 on 2021-05-15 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0007_auto_20210513_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 12, 25, 32, 128599), verbose_name='创建时间'),
        ),
    ]
