# Generated by Django 3.1.4 on 2021-05-17 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0012_auto_20210517_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 11, 40, 30, 273620), verbose_name='创建时间'),
        ),
    ]
