# Generated by Django 3.1.4 on 2021-05-17 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbase', '0016_auto_20210517_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 25, 20, 659219), verbose_name='创建时间'),
        ),
    ]
