# Generated by Django 3.1.4 on 2021-04-20 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='发送人')),
                ('receiver', models.EmailField(max_length=254, verbose_name='接收人')),
                ('about', models.CharField(max_length=20, verbose_name='主题')),
                ('text', models.CharField(max_length=50, verbose_name='正文')),
                ('read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 12, 24, 35, 615501), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
            },
        ),
    ]
