# Generated by Django 3.1.4 on 2021-03-13 06:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=20, verbose_name='主题')),
                ('text', models.CharField(max_length=50, verbose_name='正文')),
                ('read', models.BooleanField(verbose_name='是否已读')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 3, 13, 14, 1, 44, 42402), verbose_name='发送时间')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_mails', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
            },
        ),
    ]
