# Generated by Django 2.2.5 on 2022-04-14 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(verbose_name='类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 1, 4, 274326), verbose_name='时间')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='内容id')),
                ('content', models.CharField(max_length=50, verbose_name='文字描述')),
                ('involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='涉及用户')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=20, verbose_name='主题')),
                ('text', models.CharField(max_length=50, verbose_name='正文')),
                ('read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 4, 14, 12, 1, 4, 274326), verbose_name='发送时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
            },
        ),
    ]
