# Generated by Django 3.1.4 on 2021-05-17 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 30, 59, 5179), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 12, 30, 59, 5179), verbose_name='时间'),
        ),
    ]
