# Generated by Django 3.1.4 on 2021-03-13 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 14, 9, 56, 713358), verbose_name='发送时间'),
        ),
    ]
