# Generated by Django 3.1.4 on 2021-04-08 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20210313_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 14, 42, 741216), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
