# Generated by Django 3.1.4 on 2021-04-16 02:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20210408_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='receive',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='send',
        ),
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.EmailField(default='admin@admin.com', max_length=254, verbose_name='接收人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.EmailField(default='admin@admin.com', max_length=254, verbose_name='发送人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 10, 43, 41, 760054), verbose_name='发送时间'),
        ),
    ]
